config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks',
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :users
  resources :posts
  resources :users_followers, only: [:create, :destroy, :update]
  resources :likes, only: [:create, :destroy, :update]
  resources :comments, only: [:create, :destroy, :update, :edit]
  # Defines the root path route ("/")
  root "posts#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, presence: true, length: { minimum: 3, maximum: 20 }
  has_many :posts, foreign_key: "author_id", dependent: :destroy

  # followers
  has_many :users_followers, dependent: :destroy, foreign_key: :user_id
  has_many :followers, through: :users_followers, source: :follower

  has_many :pending_followers, -> { UsersFollower.pending }, through: :users_followers, source: :follower
  has_many :accepted_followers, -> { UsersFollower.accepted }, through: :users_followers, source: :follower
  has_many :denied_followers, -> { UsersFollower.denied }, through: :users_followers, source: :follower

  # followings
  has_many :users_followings, dependent: :destroy, foreign_key: :follower_id, class_name: 'UsersFollower'
  has_many :followings, through: :users_followings, source: :user

  has_many :pending_followings, -> { UsersFollower.pending }, through: :users_followings, source: :user
  has_many :accepted_followings, -> { UsersFollower.accepted }, through: :users_followings, source: :user
  has_many :denied_followings, -> { UsersFollower.denied }, through: :users_followings, source: :user

  # likes
  has_many :likes, dependent: :destroy

  # comments
  has_many :comments, dependent: :destroy
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  layout 'registration'
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  layout 'registration'
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action -> { @user = User.find(params[:id])}, only: [:show]

  def show
    # @posts = @user.posts
  end

  def index
    @users = User.all
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<div class="user">
  <h3 class="link_profile"><%= link_to "@#{user.username.upcase}", user%></h3>
  <% unless current_user == user then %>
    <h3><%= link_to "Follow", users_followers_path(user: user), data: {turbo_method: :post}%></h3>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="users"><%= render @users %></div>

app/views/users/show.html.erb
<% content_for :top_links do %>
  <div class="profile_links">
    <%= link_to 'Edit Profile', edit_user_registration_path %>
    <%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete } %>
    <%= link_to "Followers",  edit_user_registration_path%>
  </div>
<% end %>
<div id="profile">
  <div>
    <div id="profile_pic">
      profile pic
    </div>
    <%= render @user %>
    <div class="posts">
      <h3>User posts:</h3>
      <%= render @user.posts %>
    </div>
  </div>
  <div class="user_followers">
    <h3>Followers: </h3>
    <%= render "users_followers/followers", followers: @user.accepted_followers %>
    <% if current_user == @user %>
      <h3>Friends request: </h3>
      <%= render "users_followers/followers", followers: @user.pending_followers %>
    <% end %>
    <% if current_user == @user %>
      <h3>Denied request: </h3>
      <%= render "users_followers/followers", followers: @user.denied_followers %>
    <% end %>
    <h3>Following: </h3>
    <%= render "users_followers/followers", followers: @user.accepted_followings %>
    <% if current_user == @user %>
      <h3>Pending followings: </h3>
      <%= render "users_followers/followers", followers: @user.pending_followings %>
    <% end %>
    <% if current_user == @user %>
      <h3>Denied followings: </h3>
      <%= render "users_followers/followers", followers: @user.denied_followings %>
    <% end %>
  </div>
</div>
<%# <% if current_user == comment.author then%> %>
<%# <ul class="navigation"> %>
<%# <li><%= link_to "Edit", edit_comment_path(comment, post_id: post.id)</li> %> %>
<%# <li><%= link_to "Delete", comment_path(id: comment.id), data: {turbo_method: :delete} %></li>
%>
<%# </ul> %>
<%# <% end %> %>