config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks',
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :users
  resources :posts
  resources :users_followers, only: [:create, :destroy, :update]
  resources :likes, only: [:create, :destroy, :update]
  resources :comments, only: [:create, :destroy, :update, :edit]
  # Defines the root path route ("/")
  root "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: "User"
  validates :title, length: { minimum: 3, maximum: 20}
  validates :author, :title, :body, presence: true
  validates :body, length: { minimum: 20, maximum: 300}

  has_many :likes, dependent: :destroy

  has_many :comments, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action -> { @post = Post.find(params[:id]) }, only: [:show, :destroy, :update, :edit]

  def index
    @posts = Post.all
    @comment = Comment.new
  end
  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
    @comment = Comment.new
  end
  def new
    @post = Post.new
  end
  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:notice] = "New post created successfully"
      redirect_to @post
    else
      render new_post_path(@post), status: :unprocessable_entity
    end
  end
  def edit
  end
  def update
    if @post.update(post_params)
      flash[:notice] = "Post was successfully updated."
      redirect_to @post
    else
      render :edit, status: :unprocessable_entity
    end
  end
  def destroy
    if @post.destroy
      flash[:notice] = "Post destoyed succesfully."
      redirect_to posts_path
    else
      flash[:error] = "Post couldnt be destroyed."
      render posts_path
    end
  end
  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<% if post.errors.any? then %>
  <div class="errors">
    <h2>There were some errors with the posts: </h2>
    <ol style="color: red">
      <% post.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ol>
  </div>
<% end %>
<%= form_with model: post, class: "post_form" do |f| %>
  <%= f.label :title, "Title:" %>
  <%= f.text_field :title, autofocus: true, placeholder: "Please enter title here."%>
  <%= f.label :body, "Content:" %>
  <%= f.text_area :body, placeholder: "Please enter body of post here."%>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="post">
  <div class="basic_info">
    <h3 class="link_profile"><%= link_to "@#{post.author.username}", post.author%></h3>
    <h3>
      Title: <%= post.title %>
    </h3>
    <p class="content">
      <%= post.body %>
    </p>
    <div class="comments">
      <% post.comments.each do |comment| %>
        <div class="comment">
          <div>
            <h3 class="link_profile"><%= link_to "@#{comment.author.username}", post.author%></h3>
          </div>
          <div>
            <h4><%= comment.content %></h4>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <ul class="navigation">
    <div>
      Likes: <%= post.likes.count %>
    </div>
    <li><%= link_to "Post", post %></li>
    <li><%= link_to "Like", likes_path(post_id: post.id), data: { turbo_method: :post } %></li>
    <li><%= link_to "Unlike", like_path(id: post.id), data: { turbo_method: :delete } %></li>
    <% if current_user == post.author then %>
      <li><%= link_to "Delete", post_path(post), data: { turbo_method: :delete }%></li>
      <li><%= link_to "Edit", edit_post_path(post)%></li>
    <% end %>
    <%= form_with model: @comment, class: "comment_form" do |comment_form| %>
      <%= comment_form.hidden_field :post_id, value: post.id %>
      <div>
        <%= comment_form.text_area :content, placehoder: "Please enter what your think about this post", autofocus: true, placehoder: "Enter comment here.", class: "comment_field" %>
      </div>
      <div>
        <%= comment_form.submit "Comment" %>
      </div>
    <% end %>
  </ul>
</div>

app/views/posts/edit.html.erb
<%= render "form", post: @post %>

app/views/posts/index.html.erb
<div class="posts">
  <%= render @posts %>
</div>

app/views/posts/new.html.erb
<%= render "form", post: @post %>

app/views/posts/show.html.erb
<%= render @post %>
<br>
<div class="comments">
  <% @comments.each do |comment| %>
    <div class="comment">
      <div>
        <h3>Author: <%= comment.author.username%></h3>
      </div>
      <div>
        <h4>Commented: <%= comment.content %></h4>
        <% if current_user == comment.author then%>
          <ul class="navigation">
            <li><%= link_to "Edit your comment", edit_comment_path(comment, post_id: @post.id)%></li>
            <li><%= link_to "Delete comment", comment_path(comment: comment), data: {turbo_method: :delete}%></li>
          </ul>
        <% end %>
      </div>
    </div>
  <% end %>
</div>