config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks',
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :users
  resources :posts
  resources :users_followers, only: [:create, :destroy, :update]
  resources :likes, only: [:create, :destroy, :update]
  resources :comments, only: [:create, :destroy, :update, :edit]
  # Defines the root path route ("/")
  root "posts#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instachat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'post', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'user', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%# <%= image_tag 'bird.svg', alt: 'Instachat Logo', class: 'logo' %>
    <%# <header> %>
    <div class="flash">
      <% flash.each do |key, value|%>
        <h2 class=<%= key %>> <%= value %></h2>
      <% end %>
    </div>
    <%= yield :top_links %>
    <%# </header> %>
    <main class="main_layout">
      <div class="navigation_main">
        <ul class="links">
          <h1 class="title">
            Instachat
          </h1>
          <li> <%= link_to "New Posts", posts_path%></li>
          <li> <%= link_to "Users", users_path%></li>
          <li> <%= link_to "Post something.", new_post_path %></li>
          <% unless current_user.nil? then %>
            <li> <%= link_to "Your Profile", current_user %></li>
            <li><%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete } %></li>
          <% end %>
        </ul>
      </div>
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/registration.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sign Up</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'signup', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="devise">
    <div class="image_sidebar">
      <%# <%= image_tag 'nature.jpg', alt: 'Nature foto, image sidebar', class: ' image-sidebar' %>
      <%# <%= image_tag 'nature.jpg', alt: 'Instachat Logo', class: 'logo' %>
      <div class="title_container">
        <div class="title">
          <h1>
            Instachat
          </h1>
        </div>
      </div>
      <p class="shoutout">
        Photo by: <a href="https://unsplash.com/@zorzf?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Zo Razafindramamba</a> on <a href="https://unsplash.com/photos/the-sun-is-setting-over-a-mountain-range-LquOEvDfYGo?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
      </p>
    </div>
    <main>
      <%= yield %>
    </main>
  </body>
</html>